"""add_trial_columns to the company table

Revision ID: 0e9e3309f50c
Revises: ea15f098e778
Create Date: 2025-01-26 06:13:25.097137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e9e3309f50c'
down_revision: Union[str, None] = 'ea15f098e778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('trial_start', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('trial_end', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('is_trial', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'is_trial')
    op.drop_column('companies', 'trial_end')
    op.drop_column('companies', 'trial_start')
    # ### end Alembic commands ###
