"""recreate transaction_sales table

Revision ID: 1d2cb76ae174
Revises: d856525dfaed
Create Date: 2025-01-22 17:27:28.700852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d2cb76ae174'
down_revision: Union[str, None] = 'd856525dfaed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('transactions', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transactions', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('transactions', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('transactions', 'updated_at')
    # ### end Alembic commands ###
