"""update the subscription model and the route for it  

Revision ID: 2d84160238dd
Revises: 78cda87b6e57
Create Date: 2025-01-22 16:06:19.119544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d84160238dd'
down_revision: Union[str, None] = '78cda87b6e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('created_by', sa.Integer(), nullable=True))
    op.alter_column('subscriptions', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('subscriptions', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'EXPIRED', 'CANCELLED', 'PENDING', name='subscriptionstatus'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_subscriptions_id', table_name='subscriptions')
    op.create_foreign_key(None, 'subscriptions', 'users', ['created_by'], ['id'])
    op.drop_column('subscriptions', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_index('ix_subscriptions_id', 'subscriptions', ['id'], unique=False)
    op.alter_column('subscriptions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscriptions', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('ACTIVE', 'EXPIRED', 'CANCELLED', 'PENDING', name='subscriptionstatus'),
               existing_nullable=True)
    op.alter_column('subscriptions', 'end_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('subscriptions', 'start_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('subscriptions', 'created_by')
    # ### end Alembic commands ###
