"""add password reset tokens table

Revision ID: 4ab382130e09
Revises: a34226bc59f8
Create Date: 2024-12-23 15:29:57.366606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ab382130e09'
down_revision: Union[str, None] = 'a34226bc59f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('password_reset_tokens', 'is_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
