"""adding new column in company table calld description 

Revision ID: 78cda87b6e57
Revises: 489e770e096b
Create Date: 2025-01-22 15:38:37.742736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78cda87b6e57'
down_revision: Union[str, None] = '489e770e096b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('status', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('companies_owner_id_fkey', 'companies', type_='foreignkey')
    op.create_foreign_key(None, 'companies', 'users', ['user_id'], ['id'])
    op.drop_column('companies', 'owner_id')
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('companies', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_foreign_key('companies_owner_id_fkey', 'companies', 'users', ['owner_id'], ['id'])
    op.drop_column('companies', 'user_id')
    op.drop_column('companies', 'status')
    op.drop_column('companies', 'description')
    # ### end Alembic commands ###
