"""add password reset tokens table

Revision ID: 8e2d2b07a150
Revises: 2416c0cb5e04
Create Date: 2024-12-24 03:01:12.959619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e2d2b07a150'
down_revision: Union[str, None] = '2416c0cb5e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
