"""adding to the MPESATransaction table column company_id

Revision ID: b5e4e075aa76
Revises: 1d2cb76ae174
Create Date: 2025-01-22 18:31:17.542091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e4e075aa76'
down_revision: Union[str, None] = '1d2cb76ae174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mpesa_transactions', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'mpesa_transactions', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mpesa_transactions', type_='foreignkey')
    op.drop_column('mpesa_transactions', 'company_id')
    # ### end Alembic commands ###
