"""Adding mpesa_receipt_number column to mpesa_transactions table with data migration

Revision ID: d206e7907020
Revises: b8a1fd55f3ef
Create Date: 2025-01-24 15:39:20.347505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd206e7907020'
down_revision: Union[str, None] = 'b8a1fd55f3ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'companies', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'contacts', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'contacts', 'users', ['responded_by'], ['id'])
    op.create_foreign_key(None, 'import_history', 'users', ['user_id'], ['id'])
    op.add_column('mpesa_transactions', sa.Column('mpesa_receipt_number', sa.String(), nullable=True))
    op.add_column('mpesa_transactions', sa.Column('transaction_date', sa.String(), nullable=True))
    op.add_column('mpesa_transactions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'password_reset_tokens', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'sales', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'subscriptions', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'vendors', 'users', ['created_by'], ['id'])
    op.add_column('mpesa_transactions', 
        sa.Column('mpesa_receipt_number', sa.String(), nullable=True)
    )
    op.add_column('mpesa_transactions', 
        sa.Column('transaction_date', sa.String(), nullable=True)
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendors', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.drop_column('mpesa_transactions', 'updated_at')
    op.drop_column('mpesa_transactions', 'transaction_date')
    op.drop_column('mpesa_transactions', 'mpesa_receipt_number')
    op.drop_constraint(None, 'import_history', type_='foreignkey')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_column('mpesa_transactions', 'mpesa_receipt_number')
    op.drop_column('mpesa_transactions', 'transaction_date')
    # ### end Alembic commands ###
