"""update the table for Transactions 

Revision ID: d856525dfaed
Revises: 2d84160238dd
Create Date: 2025-01-22 17:10:22.279020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd856525dfaed'
down_revision: Union[str, None] = '2d84160238dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_sales', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('transaction_sales', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('transaction_sales', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('transaction_sales', 'transaction_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transaction_sales', 'sale_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_transaction_sales_id'), 'transaction_sales', ['id'], unique=False)
    op.create_foreign_key(None, 'transaction_sales', 'companies', ['company_id'], ['id'])
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('transactions', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transactions', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('transactions', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('transactions', 'updated_at')
    op.drop_constraint(None, 'transaction_sales', type_='foreignkey')
    op.drop_index(op.f('ix_transaction_sales_id'), table_name='transaction_sales')
    op.alter_column('transaction_sales', 'sale_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transaction_sales', 'transaction_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('transaction_sales', 'created_at')
    op.drop_column('transaction_sales', 'company_id')
    op.drop_column('transaction_sales', 'id')
    # ### end Alembic commands ###
