"""add company_id to mpesa_transactions with default

Revision ID: dc003bb8eab8
Revises: b5e4e075aa76
Create Date: 2025-01-22 18:39:10.280828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc003bb8eab8'
down_revision: Union[str, None] = 'b5e4e075aa76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mpesa_transactions', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mpesa_transactions', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mpesa_transactions', type_='foreignkey')
    op.drop_column('mpesa_transactions', 'company_id')
    # ### end Alembic commands ###
