"""remove mpesa receipt columns

Revision ID: ea15f098e778
Revises: 2ce485ebbe51
Create Date: 2025-01-24 15:58:39.247366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea15f098e778'
down_revision: Union[str, None] = '2ce485ebbe51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mpesa_transactions', 'mpesa_receipt_number')
    op.drop_column('mpesa_transactions', 'transaction_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mpesa_transactions', sa.Column('transaction_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mpesa_transactions', sa.Column('mpesa_receipt_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
