"""add mpesa transactions table with named enum

Revision ID: 10f203510bf7
Revises: 571ebd56e229
Create Date: 2025-01-13 20:54:40.831222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10f203510bf7'
down_revision: Union[str, None] = '571ebd56e229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stk_push_id', table_name='stk_push')
    op.drop_table('stk_push')
    op.drop_constraint('mpesa_transactions_transaction_id_fkey', 'mpesa_transactions', type_='foreignkey')
    op.drop_column('mpesa_transactions', 'transaction_id')
    op.drop_column('mpesa_transactions', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mpesa_transactions', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('mpesa_transactions', sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('mpesa_transactions_transaction_id_fkey', 'mpesa_transactions', 'transactions', ['transaction_id'], ['id'])
    op.create_table('stk_push',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('merchant_request_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('checkout_request_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('trans_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='stk_push_pkey')
    )
    op.create_index('ix_stk_push_id', 'stk_push', ['id'], unique=False)
    # ### end Alembic commands ###
