"""Adding ImportHistory modal (Table)

Revision ID: cbe070d40e0c
Revises: 9a42d0828907
Create Date: 2024-11-11 17:58:01.358581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbe070d40e0c'
down_revision: Union[str, None] = '9a42d0828907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
