"""add vendor_id to products

Revision ID: f222620bb575
Revises: d6c7e8857666
Create Date: 2024-12-23 22:12:50.448138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f222620bb575'
down_revision: Union[str, None] = 'd6c7e8857666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_id', table_name='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_products_id', 'products', ['id'], unique=False)
    # ### end Alembic commands ###
