"""add vendor_id to products

Revision ID: f435af1eec5f
Revises: 8e1295ef252a
Create Date: 2024-12-23 19:43:14.021186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f435af1eec5f'
down_revision: Union[str, None] = '8e1295ef252a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('vendor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'vendors', ['vendor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'vendor_id')
    # ### end Alembic commands ###
